x-python-service:
  &x-python-service
  image: 'meta-python'
  depends_on:
    redis:
      condition: service_healthy
    mysql:
      condition: service_healthy
  env_file:
    - .env
  volumes:
    - ./bot_ui:/app/bot_ui
    - ./core:/app/core
    - ./scripts:/app/scripts
    - /etc/letsencrypt:/etc/certbot:ro
  networks:
    - internal


services:
  telegram-bot:
    <<: *x-python-service
    build:
      context: .
      dockerfile: bot_ui/config/Dockerfile
    ports:
      - "433:433"
    command: ["python3", "bot_ui/__init__.py"]

  worker:
    <<: *x-python-service
    command: ["celery", "-A", "core.celery_app:app", "worker", "-Q", "wallet-fetch-queue,noticed-wallets-upload-queue", "--loglevel=info"]

  transaction-lookup:
    build:
      context: transaction-lookup
      dockerfile: build/Dockerfile.worker
    env_file:
      - transaction-lookup/.env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - internal

  redis:
    image: "redis:7.2.4-alpine"
    ports:
      - "6380:6379"
    volumes:
      - volume-queue:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - internal

  mysql:
    image: "mysql:8.3.0"
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - volume-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -hlocalhost -uroot -p${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - internal

volumes:
  volume-data:
  volume-queue:


networks:
  internal:
