x-python-service:
  &x-python-service
  user: "1000:1000"
  depends_on:
    redis:
      condition: service_healthy
    mysql:
      condition: service_healthy
  networks:
    - internal


services:
  telegram-bot:
    <<: *x-python-service
    build:
      context: .
      dockerfile: Dockerfile
      target: telegram-bot
    env_file:
      - bot_ui/config/.env
      - core/config/.env
    ports:
      - "433:433"
    volumes:
      - ./bot_ui:/app/bot_ui
      - ./core:/app/core
      - /etc/letsencrypt:/etc/certbot:ro
    command: ["python3", "bot_ui/__init__.py"]

  transaction-lookup:
    build:
      context: transaction-lookup
      dockerfile: build/Dockerfile.worker
    env_file:
      - transaction-lookup/.env
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - internal

  wallet-indexer:
    <<: *x-python-service
    build:
      context: .
      dockerfile: Dockerfile
      target: wallet-indexer
    image: wallet-indexer
    env_file:
      - wallet_indexer/config/.env
      - core/config/.env
    restart: on-failure
    command: [
      "celery",
      "-A",
      "wallet_indexer.celery_app:app",
      "worker",
      "-Q",
      "wallet-fetch-queue",
      "--loglevel=info"
    ]
    environment:
      - WORKER_CONCURRENCY=8
    volumes:
      - ./core:/app/core
      - ./wallet_indexer:/app/wallet_indexer

  load-noticed-wallets:
    <<: *x-python-service
    image: wallet-indexer
    env_file:
      - wallet_indexer/config/.env
      - core/config/.env
    restart: on-failure
    command: [
      "celery",
      "-A",
      "wallet_indexer.celery_app:app",
      "worker",
      "-Q",
      "noticed-wallets-upload-queue",
      "--loglevel=info"
    ]
    environment:
      - WORKER_CONCURRENCY=1
      - LOAD_WALLETS=1
    volumes:
      - ./core:/app/core
      - ./wallet_indexer:/app/wallet_indexer

  community-manager:
    <<: *x-python-service
    build:
      context: .
      dockerfile: Dockerfile
      target: community-manager
    env_file:
      - community_manager/config/.env
      - core/config/.env
    command: [
      "celery",
      "-A",
      "community_manager.celery_app:app",
      "worker",
      "-Q",
      "system-queue",
      "--loglevel=info"
    ]
    volumes:
      - ./community_manager:/app/community_manager
      - ./core:/app/core

  api:
    <<: *x-python-service
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    env_file:
      - api/config/.env
      - core/config/.env
    volumes:
      - ./api:/app/api
      - ./core:/app/core
    command: ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "80", "--workers", "4"]

  redis:
    image: "redis:7.2.4-alpine"
    ports:
      - "6380:6379"
    volumes:
      - volume-queue:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - internal

  mysql:
    image: "mysql:8.3.0"
    ports:
      - "3307:3306"
    env_file:
      - core/config/.env
    volumes:
      - volume-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -hlocalhost -uroot -p${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - internal

  nginx:
    image: "nginx:stable"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    networks:
      - internal
    depends_on:
      - api

volumes:
  volume-data:
  volume-queue:


networks:
  internal:
