from pathlib import Path

POOL_TIMEOUT = 30
DEFAULT_CONNECT_TIMEOUT = 180
DEFAULT_EXPIRY_TIMEOUT_MINUTES = 30

DEFAULT_WALLET_RATING = 888888
DEFAULT_WALLET_BALANCE = 0

CUSTOM_TITLE_TEMPLATE = "8x{rank}"

STATIC_PATH = Path(__file__).parent / "static"
DEFAULTS_PATH = STATIC_PATH / "defaults"
JETTON_LOGO_SUB_PATH = "jettons"
JETTON_LOGO_PATH = STATIC_PATH / JETTON_LOGO_SUB_PATH
DEFAULT_JETTON_LOGO_PATH = DEFAULTS_PATH / "jetton.webp"
NFT_LOGO_SUB_PATH = "nfts"
NFT_LOGO_PATH = STATIC_PATH / NFT_LOGO_SUB_PATH
DEFAULT_NFT_LOGO_PATH = DEFAULTS_PATH / "nft.webp"
