"""nullable jetton nft path

Revision ID: 21490b140b9f
Revises: 084f2df0832d
Create Date: 2025-04-04 13:03:56.858552

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "21490b140b9f"
down_revision: Union[str, None] = "084f2df0832d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jetton", "logo_path", existing_type=mysql.VARCHAR(length=290), nullable=True
    )
    op.alter_column(
        "nft_collection",
        "logo_path",
        existing_type=mysql.VARCHAR(length=290),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "nft_collection",
        "logo_path",
        existing_type=mysql.VARCHAR(length=290),
        nullable=False,
    )
    op.alter_column(
        "jetton", "logo_path", existing_type=mysql.VARCHAR(length=290), nullable=False
    )
    # ### end Alembic commands ###
